database:
  driver: mysql
  drivers:
    mysql:
      connections:
        - auth:
            host: MYSQL_DB_HOST
            port: MYSQL_DB_PORT
            name: MYSQL_DB_NAME
            user: MYSQL_DB_USER
            pass: MYSQL_DB_PASS
          tables:
            backup:
              - users
            ignore:
              - migrations
          create_db_query: true

file_storage:
  driver: s3
  upload_backups: true
  - auth:
    access_key_id: S3_ACCESS_KEY_ID
    secret_access_key: S3_SECRET_ACCESS_KEY

root_backup_dir: /tmp/multiback/
