database:
  driver: mysql
  drivers:
    mysql:
      connections:
        - auth:
            host: MYSQL_DB_HOST
            port: MYSQL_DB_PORT
            name: MYSQL_DB_NAME
            user: MYSQL_DB_USER
            pass: MYSQL_DB_PASS
          tables:
            backup:
              - users
            ignore:
              - migrations
